[env:esp32dev]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

build_flags =
    ; --- TFT ILI9488 SPI (shared VSPI bus) ---
    -D USER_SETUP_LOADED=1
    -D ILI9488_DRIVER=1
    -D TFT_MISO=-1
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=22
    -D TFT_RST=4
    -D TFT_BL=13
    -D TFT_BACKLIGHT_ON=HIGH
    -D SPI_FREQUENCY=27000000
    -D SPI_READ_FREQUENCY=6000000
    -D SUPPORT_TRANSACTIONS=1

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    nrf24/RF24 @ ^1.4.10
    bblanchon/ArduinoJson@^7.0.4
